se_payment.settings:
  type: mapping
  label: 'Payment settings'
  mapping:
    vocabulary:
      type: string
      label: 'Taxonomy vocab for default payment types.'
    main_contact_term:
      type: string
      label: 'Taxonomy term for the default payment type.'
